// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from './providers';
import { ClerkProvider } from "@clerk/nextjs";
<<<<<<< HEAD
// //import ConvexClientProvider from "@/Components/providers/ConvexClientProvider";
// import Footer from "@/Components/Footer";
// import { Toaster } from "react-hot-toast";
=======
import { Toaster } from 'react-hot-toast';
import UserDataSync from '@/components/UserDataSync';
import Footer from "@/components/Footer";
>>>>>>> 1aa82f4 (make the change in the price page)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//import { Providers } from './providers';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <ClerkProvider>
      <body>
          <Providers>{children}</Providers>
        </body>
      </ClerkProvider>
    </html>
=======
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen flex flex-col">
          <UserDataSync />
          <Toaster />
          <Providers>
            <div className="flex-1 flex flex-col">
              {children}
            </div>
            <Footer />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
>>>>>>> 1aa82f4 (make the change in the price page)
  );
}